language: python
python: '2.7'
env:
- TOXENV=py26
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=flake8
install:
- pip install tox
script:
- tox
matrix:
  fast_finish: true
before_install: pip install codecov
after_success: codecov
